export const Metrics = [
  {
    title: 'LEU 120S',
    parameters: [
      {
        name: '-',
        color: '#EFEBC6',
        _id: 1,
        meaning: 'No White blood Cells in Urine',
        results:
          'Results show no abnormalities check website for home remedies on how to keep healthy.',
      },
      {
        name: '15+',
        color: '#e8ddc9',
        _id: 2,
        meaning: 'Mild number of White Blood Cells In Urine',
        results: 'Recommendation see a doctor',
      },
      {
        name: '70+',
        color: '#dad4c6',
        _id: 3,
        meaning: 'Mild number of White Blood Cells In Urine',
        results: 'Recommendation see a doctor',
      },
      {
        name: '125++',
        color: '#e7c6d9',
        _id: 4,
        meaning: 'Moderate White Blood Cells in urine',
        results: 'Recommendation see a doctor',
      },
      {
        name: '500++',
        color: '#ad9fb9',
        _id: 5,
        meaning: 'Excessive White Blood Cells in urine',
        results: 'Recommendation see a doctor',
      },
    ],
  },
  {
    title: 'NIT 60S',
    parameters: [
      {
        name: '-',
        color: '#fbf6e0',
        _id: 6,
        meaning: 'No Bacteria in Urine',
        results:
          'Results show no abnormalities check websitefor home remedies on how to keep healthy.',
      },
      {
        name: '( - )',
        color: '#fee0e5',
        _id: 7,
        meaning: 'Few of Bacteria in Urine',
        results: 'Recommendation see a doctor',
      },
      {
        name: 'PINK ROSE',
        color: '#fafafa',
        _id: 8,
        meaning: 'Some of Bacteria in Urine',
        results: 'Recommendation see a doctor',
      },
      {
        name: 'ROSAD',
        color: '#fafafa',
        _id: 9,
        meaning: 'Mild of Bacteria in Urine',
        results: 'Recommendation see a doctor',
      },
      {
        name: 'ROSAD ROSA',
        color: '#fafafa',
        _id: 10,
        meaning: 'Moderate of Bacteria in Urine',
        results: 'Recommendation see a doctor',
      },
      {
        name: 'LYRESE ROD',
        color: '#fafafa',
        _id: 11,
        meaning: 'Moderate of Bacteria in Urine',
        results: 'Recommendation see a doctor',
      },
      {
        name: '+',
        color: '#d86ca0',
        _id: 12,
        meaning: 'Excessive of Bacteria in Urine',
        results: 'Recommendation see a doctor',
      },
    ],
  },
  {
    title: 'URO 60S',
    parameters: [
      {
        name: '0.2(3.5)',
        color: '#fbd9be',
        _id: 13,
        meaning: 'No Bilinogen in Urine',
        results:
          'Results show no abnormalities check website for home remedies on how to keep healthy',
      },
      {
        name: '1(17)',
        color: '#f8cab7',
        _id: 14,
        meaning: 'Little Bilinogen in Urine',
        results: `Results show no abnormalities check website for home remedies on how to keep healthy.`,
      },
      {
        name: '2(35)',
        color: '#f1a58e',
        _id: 15,
        meaning: 'Mild Bilinogen In urine',
        results: 'Recommendation see a doctor',
      },
      {
        name: '4(70)',
        color: '#d8868a',
        _id: 16,
        meaning: 'Moderate Bilinogen in urine',
        results: 'Recommendation see a doctor',
      },
      {
        name: '8(140)',
        color: '#e17d95',
        _id: 17,
        meaning: 'Severe Bilinogen in urine',
        results: 'Recommendation see a doctor',
      },
      {
        name: '12(200)',
        color: '#e88395',
        _id: 18,
        meaning: 'Severe Bilinogen in urine',
        results: 'Recommendation see a doctor',
      },
      {
        name: 'mg/dl(umo/L)',
        color: '#fafafa',
        _id: 19,
        meaning: 'Very severe Bilinogen in urine',
        results: 'Recommendation see a doctor',
      },
    ],
  },
  {
    title: 'PRO 60S',
    parameters: [
      {
        name: '-',
        color: '#dce977',
        _id: 20,
        meaning: 'No Protein in Urine',
        results: `Results show no abnormalities check website for home remedies on how to keep healthy`,
      },
      {
        name: '15(.15)+-',
        color: '#bad36d',
        _id: 21,
        meaning: 'LITTLE Protein in Urine',
        results: `Recommendation see a doctor`,
      },
      {
        name: '30(0.3)+',
        color: '#A5C177',
        _id: 22,
        meaning: 'Mild Protein Present in Urine',
        results: `Recommendation see a doctor`,
      },
      {
        name: '100(1.0)++',
        color: '#a5c177',
        _id: 23,
        meaning: 'Mild Protein Present in Urine',
        results: 'Recommendation see a doctor',
      },
      {
        name: '300(3.0)+++',
        color: '#70AF9A',
        _id: 24,
        meaning: 'Severe Protein in Urine',
        results: 'Recommendation see a doctor',
      },
      {
        name: '2000(20)+++++',
        color: '#599C8A',
        _id: 25,
        meaning: 'Very Severe Protein in Urine',
        results: 'Recommendation see a doctor',
      },
    ],
  },
  {
    title: 'PH 60S',
    parameters: [
      {
        name: '5.0',
        color: '#f1814a',
        _id: 27,
        meaning: 'Very Acidic',
        results: `Recommendation see a doctor`,
      },
      {
        name: '6.0',
        color: '#eca452',
        _id: 28,
        meaning: 'Slightly Acidic',
        results: `Recommendation see a doctor`,
      },
      {
        name: '6.5',
        color: '#dcc053',
        _id: 29,
        meaning: 'Normal Range of PH',
        results: `Results show no abnormalities check website for home remedies on how to keep healthy.`,
      },

      {
        name: '7.0',
        color: '#b5c15b',
        _id: 30,
        meaning: 'Normal Range of PH',
        results: `Results show no abnormalities check website for home remedies on how to keep healthy.`,
      },
      {
        name: '7.5',
        color: '#81a54d',
        _id: 31,
        meaning: 'Normal Range of PH',
        results: `Results show no abnormalities check website for home remedies on how to keep healthy.`,
      },
      {
        name: '8.0',
        color: '#4c9b6b',
        _id: 33,
        meaning: 'Moderate Alkaline',
        results: `Recommendation see a doctor`,
      },
      {
        name: '9.0',
        color: '#1c7a7c',
        _id: 34,
        results: 'Very Alkaline',
        meaning: `Recommendation see a doctor`,
      },
    ],
  },
  {
    title: 'BLO 60S',
    parameters: [
      {
        name: '-',
        color: '#e5be3f',
        _id: 35,
        meaning: 'No Blood in Urine',
        results: `Results show no abnormalities check website for home remedies on how to keep healthy.`,
      },
      {
        name: '+-',
        color: '#e6bd38',
        _id: 36,
        meaning: 'Little Blood in Urine',
        results: `Recommendation see a doctor`,
      },
      {
        name: '+',
        color: '#dbc946',
        _id: 37,
        meaning: 'Some Blood in Urine',
        results: `Recommendation see a doctor`,
      },
      {
        name: '++',
        color: '#c1bf44',
        _id: 38,
        meaning: 'Mild blood in Urine',
        results: `Recommendation see a doctor`,
      },
      {
        name: '+++',
        color: '#92ab45',
        _id: 39,
        meaning: 'Moderate blood in Urine',
        results: 'Recommendation see a doctor',
      },
      {
        name: '5-10',
        color: '#578846',
        _id: 40,
        meaning: 'Alot of blood in Urine',
        results: 'Recommendation see a doctor',
      },
      {
        name: '50-Ey/L',
        color: '#39533a',
        _id: 41,
        meaning: 'Excessive blood in Urine',
        results: `Recommendation see a doctor`,
      },
    ],
  },
  {
    title: 'SG 45S',
    parameters: [
      {
        name: '1.000',
        color: '#11422f',
        _id: 42,
        meaning: 'Dillute Urine',
        results: `Recommendation see a doctor`,
      },
      {
        name: '1.005',
        color: '#4D5926',
        _id: 44,
        meaning: 'Normal Concetration',
        results: `Recommendation see a doctor`,
      },
      {
        name: '1.010',
        color: '#737744',
        _id: 45,
        meaning: 'Normal Urine concetration',
        results: `Results show no abnormalities check website for home remedies on how to keep healthy.`,
      },
      {
        name: '1.015',
        color: '#85894B',
        _id: 46,
        meaning: 'Normal Urine concetration',
        results: `Results show no abnormalities check website for home remedies on how to keep healthy.`,
      },
      {
        name: '1.020',
        color: '#938006',
        _id: 47,
        meaning: 'Normal Urine concetration',
        results: `Results show no abnormalities check website for home remedies on how to keep healthy.`,
      },
      {
        name: '1.025',
        color: '#A29B25',
        _id: 48,
        meaning: 'Normal Conccetrated',
        results: `Results show no abnormalities check website for home remedies on how to keep healthy.`,
      },
      {
        name: '1.030',
        color: '#D8B50F',
        _id: 48.1,
        meaning: 'Slightly Concetrated',
        results: `Results show no abnormalities check website for home remedies on how to keep healthy.`,
      },
    ],
  },
  {
    title: 'KET 40S',
    parameters: [
      {
        name: '-',
        color: '#f1ae93',
        _id: 49,
        meaning: 'No Ketones in Urine',
        results: `Results show no abnormalities check website for home remedies on how to keep healthy.`,
      },
      {
        name: '5(0,5)+-',
        color: '#ec9995',
        _id: 50,
        meaning: 'Very Few Ketones in Urine',
        results: `Results show no abnormalities check websitefor home remedies on how to keep healthy.`,
      },
      {
        name: '15(1.5)+-',
        color: '#da877f',
        _id: 51,
        meaning: 'Few Ketones in Urine',
        results: `Recommendation see a doctor`,
      },
      {
        name: '40(4.0)+-',
        color: '#cb726a',
        _id: 52,
        meaning: 'Some Ketones in Urine',
        results: `Recommendation see a doctor`,
      },
      {
        name: '80(8.0)+++',
        color: '#945069',
        _id: 53,
        meaning: 'Many Ketones in Urine',
        results: `Recommendation see a doctor`,
      },
      {
        name: '160(16)+++',
        color: '#6d3454',
        _id: 54,
        meaning: 'Very Many Ketones in Urine',
        results: `Very Many Ketones in Urine`,
      },
    ],
  },
  {
    title: 'BIL 30S',
    parameters: [
      {
        name: '-',
        color: '#fde7ae',
        _id: 55,
        meaning: 'No Bilirubin',
        results: `Results show no abnormalities check website for home remedies on how to keep healthy.`,
      },
      {
        name: '1(17)+-',
        color: '#f8c89c',
        _id: 56,
        meaning: 'Little Bilirubin',
        results: `Recommendation see a doctor`,
      },
      {
        name: '2(35)++',
        color: '#c3a485',
        _id: 57,
        meaning: 'Alot Bilirubin',
        results: `Recommendation see a doctor`,
      },
      {
        name: '4(70)+++',
        color: '#ac8e84',
        _id: 58,
        meaning: 'Very Much Bilirubin',
        results: `Recommendation see a doctor`,
      },
    ],
  },
  {
    title: 'GLU 30S',
    parameters: [
      {
        name: '-',
        color: '#97d0c7',
        _id: 59,
        meaning: 'No sugar in Urine',
        results: `Results show no abnormalities check website for home remedies on how to keep healthy.`,
      },
      {
        name: '100(5)+-',
        color: '#82c597',
        _id: 60,
        meaning: 'Little Sugar in Urine',
        results: `Recommendation see a doctor`,
      },
      {
        name: '250(15)+',
        color: '#6aad4e',
        _id: 61,
        meaning: 'Moderate Sugar in Urine',
        results: `Recommendation see a doctor`,
      },
      {
        name: '250(15)+',
        color: '#938006',
        _id: 62,
        meaning: 'High Sugar in Urine',
        results: `Recommendation see a doctor`,
      },
      {
        name: '500(30)+_',
        color: '#976831',
        _id: 63,
        meaning: 'Very High Sugar in Urine',
        results: `Recommendation see a doctor`,
      },
      {
        name: '1000(60)+++',
        color: '#7b502c',
        _id: 64,
        meaning: 'Extremely High Sugar in Urine',
        results: `Recommendation see a doctor`,
      },
    ],
  },
];
